version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn dev
    environment:
      NODE_ENV: development
    ports:
      - '9229:9229'
    volumes:
      - .:/app
      